### ISSUE TITLE
demo index mentioned in readme doesn't exist

### ISSUE THREAD

**Issue by Haroenv** [meilisearch/instant-meilisearch#1005]
**Description**

On https://codesandbox.io/s/ms-is-mese9?fontsize=14&hidenavigation=1&theme=dark&file=/src/app.js:173-340 I see 

```
  "https://ms-adf78ae33284-106.lon.meilisearch.io/",
    "a63da4928426f12639e19d62886f621130f3fa9ff3c7534c5d179f0f51c4f303",
```

and on the readme (same for the other flavours) I see

```
  "https://integration-demos.meilisearch.com",
  "q7QHwGiX841a509c8b05ef29e55f2d94c02c00635f729ccf097a734cbdf7961530f47c47"
```

**Expected behavior**

All documented examples to work

**Current behavior**

The "integration demos" don't work

**Screenshots or Logs**

<img width="1440" alt="Screenshot 2023-02-20 at 15 27 11" src="https://user-images.githubusercontent.com/6270048/220133571-9fa6eadd-e60e-4a95-b64e-68c5adeb933e.png">

**Environment (please complete the following information):**
- OS: macOS
- Browser: Safari Release 161 (Safari 16.4, WebKit 18615.1.17.6)
- Meilisearch version: ?
- instant-meilisearch version: 0.11.0
- instantsearch.js version: all

**Comment by bidoubiwa** [comment]
Thanks a lot for pointing this out 🙏 fixed in #1006
