### ISSUE TITLE
refinementList missing values when too many items in the list.

### ISSUE THREAD

**Issue by kamopeter** [meilisearch/instant-meilisearch#1050]
Hello,

I've got a problem with the rerfinementList.

I use instant-meilisearch to list products.
We have more than 13000  products and approximetly 140 brands in the refinementList.
I realised when I set the price range filter to a smaller range I can see the end of the refinementList, if I use the default, these brands disappear.

Please help me, how can I solve this problem.

I'd like to show all of the brands which in the index.

Thanks

**Comment by bidoubiwa** [comment]
Hey @kamopeter 

Two things are possible here:

First, in Meilisearch there is [a setting `faceting`](https://docs.meilisearch.com/reference/api/settings.html#faceting) to set the maximum facet values returned. Which defaults to 100.
You can update this number using the [update method](https://docs.meilisearch.com/reference/api/settings.html#update-faceting-settings).

Example: 
```js
client.index('books').updateFaceting({ maxValuesPerFacet: 140 })
``` 

The second thing is, you can set a `limit` parameter in your RefinementList widget to choose the number of facets you want to showcase [see doc](https://www.algolia.com/doc/api-reference/widgets/refinement-list/js/#widget-param-limit).

Example:
```js
refinementList({
  //...
  limit: 140,
});
```

Does this help?

**Comment by kamopeter** [comment]
Thanks for your answer! It helped me.
That was the third time, when I get a quick answer.
I'm gratefull!

**Comment by bidoubiwa** [comment]
Closing this as it is resolved ✨
