### ISSUE TITLE
Is there a rank point when sorting?

### ISSUE THREAD

**Issue by kon3ko** [meilisearch/instant-meilisearch#1064]
I see now there are multi search indexs
But my goal is to show all search results. sorted by closest proximity

In meilisearch system is it possible to show rank point in `hits` items when using multi indexs?

**Comment by bidoubiwa** [comment]
Hey @kon3ko, your suggestion is in discussion on the product repository.

You can find the related thread here: https://github.com/meilisearch/product/discussions/594
