### ISSUE TITLE
Filtering using a key which has spaces (e.g. "In Stock") raises an error

### ISSUE THREAD

**Issue by rub1e** [meilisearch/instant-meilisearch#1083]
**Description**
Filtering using a key which has spaces (e.g. "Lens Color") raises an error

**Expected behavior**
You should be able to filter using keys with spaces

**Current behavior**
MeilisearchApiError is returned

**Screenshots or Logs**
```
[MeiliSearchApiError]: Inside `.queries[0]`: Was expecting an operation `=`, `!=`, `>=`, `>`, `<=`, `<`, `IN`, `NOT IN`, `TO`, `EXISTS`, `NOT EXISTS`, `_geoRadius`, or `_geoBoundingBox` at `Lens Color=\"Red\"`.
1:17 Lens Color="Red"
    at /home/rubie/oco-hydrogen/node_modules/@meilisearch/instant-meilisearch/dist/instant-meilisearch.umd.js:359:25
    at step (/home/rubie/oco-hydrogen/node_modules/@meilisearch/instant-meilisearch/dist/instant-meilisearch.umd.js:266:25)
    at Object.next (/home/rubie/oco-hydrogen/node_modules/@meilisearch/instant-meilisearch/dist/instant-meilisearch.umd.js:215:22)
    at fulfilled (/home/rubie/oco-hydrogen/node_modules/@meilisearch/instant-meilisearch/dist/instant-meilisearch.umd.js:174:32)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'invalid_search_filter',
  type: 'invalid_request',
  link: 'https://docs.meilisearch.com/errors#invalid_search_filter',
  httpStatus: 400
}
```

**Environment (please complete the following information):**
- OS: Ubuntu
- Browser: All
- Meilisearch version: 1.1
- instant-meilisearch version: 0.12.0
- instantsearch.js version: 4.51.1

[Edited with better example]

**Comment by oluademola** [comment]
Hello @rub1e. Sorry for the delay. I think this is due to a badly formatted filter, if you use quotes around the key or attribute it should work. For example: `"filter": "'in stock' = true"`

**Comment by rub1e** [comment]
Hi @oluademola, thanks for getting back to me. Apologies for lack of clarity, I can now see what's causing the error:

The error occurs when using the instantsearch widgets like ToggleRefinement or RefinementList.

So this causes the error

`<ToggleRefinement attribute="In Stock" />`
`<RefinementList attribute="Lens Color" />`

However I'm using the widgets from React InstantSearch Hooks so maybe this error is because this version of instant-meilisearch isn't supposed to work with the latest hooks package? In which case I'll close the issue.

**Comment by bidoubiwa** [comment]
Hey @rub1e 
Thanks for the heads-up. `instant-meilisearch` should definitely work with the latest react hook library. I'll tag this as a bug!

**Comment by rub1e** [comment]
No problem, let me know if you want me to test anything
