### ISSUE TITLE
Change node version used in CI from 16 to 18

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/instant-meilisearch#1119]
Most CI jobs are ran with node 16. These should be updated to node 18.

Example: 

https://github.com/meilisearch/instant-meilisearch/blob/bd6ec70211f7a86319a2276cb2abdf89b559ce51/.github/workflows/pre-release-tests.yml#L46-L49

**Comment by tungbq** [comment]
Created a PR https://github.com/meilisearch/instant-meilisearch/pull/1122 for this task
