### ISSUE TITLE
Usage with TypeScript

### ISSUE THREAD

**Issue by bb** [meilisearch/instant-meilisearch#118]
I'd like to use this library with TypeScript, however there do not seem to be official typings available.

Are there any plans to add typings?
If so, which would be the preferred way?
One could:
* convert the project to TypeScript (as e.g. meilisearch-js
already is in TypeScript as well),
* add separate d.ts files here inside this repository or
* add them outside e.g. at DefinitelyTyped.

<details>
<summary>Related issue which might be solved by the above</summary>

Besides the actual types I had another problem: even with the usual no-types-available approach (adding a separate .d.ts file with `declare module "@meilisearch/instant-meilisearch";`), I could not immediately use the lib with TypeScript and Webpack. Typescript claimed the Module is no function. I worked around it by modifying the source directly and exporting the function (instead of default export).

</details>

**Comment by bidoubiwa** [comment]
Hey @bb, thanks so much for this very clear review.
 
We could consider converting the project to typescript. Meanwhile, having a separate .d.ts file is a good idea! I will create an issue for converting the project. 

About the problem of the default export. We had a similar problem on meilisearch-js, we have solved it but I'm not sure I remember exactly what I did.  Do you have a fork with the type file that I could look at?  If I can figure out a way to make it work, It would be a great addition to have your type file in this repository (in which case I will tell you so you can create the PR). 

I will also open an issue to discuss the possibility of going from default export to named export. As of today, I'm not sure which is the best practice.

**Comment by bb** [comment]
I don't have anything available right now, but as you like the idea of converting the project to TS, I could prepare a PR.

**Comment by bidoubiwa** [comment]
I made the issue on name export vs default export if you want to join in the debate @bb 😄

**Comment by bidoubiwa** [comment]
Implemented by: #249
