### ISSUE TITLE
Improve tests

### ISSUE THREAD

**Issue by curquiza** [meilisearch/instant-meilisearch#12]
## State of tests

As of now we only tests a few instant-meilisearch return in `tests/base.test.js`. Those are not enough to ensure that every option of instant-meilisearch works properly.

## Solution

More integration tests should be added. In a perfect world, every parameter should be tests with different values. But we can start with an mvp of tests.

## Example

- with/without pagination widget
- with/without facets widget
- ...

**Comment by bidoubiwa** [comment]
Fixed by: #409
