### ISSUE TITLE
Unify licenses

### ISSUE THREAD

**Issue by bb** [meilisearch/instant-meilisearch#125]
I noticed the following files specify ISC while the rest of the project is MIT. Maybe those should be _changed_ to MIT (or the lines _removed_, as there's also no extra license in the playground's package.json).

* https://github.com/meilisearch/instant-meilisearch/blob/master/examples/esm/package.json#L11
* https://github.com/meilisearch/instant-meilisearch/blob/master/examples/express/package.json#L11

I'm happy to provide a PR if you tell me which way you prefer.

**Comment by curquiza** [comment]
Hello @bb!
Indeed, you're right, `MIT` would be better! We would be really glad to review your PR 😁
