### ISSUE TITLE
How to exclude 0 count facets? How to make facets stay in the list?

### ISSUE THREAD

**Issue by ayalon** [meilisearch/instant-meilisearch#126]
I have two simple questions. I created a earch prototype with algolia and I'm now trying the same code to work with meilisearch.

**First issue:**
I have have a facet called author. Every document has exactly one author. If I click on one facet, on algolia all the autors with their count remains.

Adam (10)
Abraham (5)
Rossier (1)

If I select Adam on meilisearch the result is:
**Adam (10)** (active)
Abraham (0)
Rossier (0)

How can I exclude facets with count 0? They make my result quite big.

Second issue:
And how can I realize the same behaviour like on algolia to have non-disjunktive facets?

**Adam (10)** (active)
Abraham (5) (remain selectable)
Rossier (1) (remain selectable)

Thanks for any hints.

**Comment by bidoubiwa** [comment]
Hey @ayalon. 

## First issue
About the first issue, I think it is possible using the [`transform-items`](https://www.algolia.com/doc/api-reference/widgets/refinement-list/vue/#widget-param-transform-items) option from algolia (for [vue](https://www.algolia.com/doc/api-reference/widgets/refinement-list/vue/#widget-param-transform-items), [react](https://www.algolia.com/doc/api-reference/widgets/refinement-list/react/#widget-param-transformitems), [vanilla](https://www.algolia.com/doc/api-reference/widgets/refinement-list/js/#widget-param-transformitems), ..).

If you use `vue`,  you would simply have to do something like this:
```html
    <ais-refinement-list
            :transform-items="transformItems"
            attribute="genres"
     />
```
I have only added the script on the `genres` `ais-refinement-list`. You can add them to each.

```javascript
 methods: {
      transformItems(items) {
        return items.filter(item => item.count !== 0);
      },
    },
```

This is with the script:
<img width="1189" alt="Screenshot 2020-11-09 at 14 30 17" src="https://user-images.githubusercontent.com/33010418/98547236-279e6f00-2298-11eb-8838-eb65a941c189.png">

This is without the script:
<img width="1054" alt="Screenshot 2020-11-09 at 14 30 05" src="https://user-images.githubusercontent.com/33010418/98547253-2ec57d00-2298-11eb-91f6-c0f78d8e1362.png">

## Second issue

Unfortunately, this is still something that needs to be made possible with MeiliSearch. A first try was made but it introduced other problems meilisearch/MeiliSearch#976.
I would suggest you make an issue on the MeiliSearch repository as issues are needed to know what features are asked for by the community.

**Comment by ayalon** [comment]
@bidoubiwa 👍 
Thank you very much for your response. I was aware if the transform action but I thought there must be a way to filter out the empty items on the server side. But I'm fine with filtering client side.

I will follow up the open issue you mentioned. The terminology for this behaviour is unknown to me, so I'm glad you gave me some directions.
