### ISSUE TITLE
Should we remove the ".lock" file?

### ISSUE THREAD

**Issue by curquiza** [meilisearch/instant-meilisearch#134]
We are thinking about removing (or not) the `.lock` file of this package.

Since this discussion concerns all the JS tools of the MeiliSearch organization, we created a centralized issue: https://github.com/meilisearch/integration-guides/issues/53.

If you are interested in this topic, please read it and feel free to share your (professional or not) experience with us on this main issue. Every opinion would be really helpful! 😁

**Comment by bidoubiwa** [comment]
After discussion it has been decided that yarn lock will be kept to ensure a same environment for all contributors
