### ISSUE TITLE
Add attributesToRecieve as an param

### ISSUE THREAD

**Issue by aaronschweig** [meilisearch/instant-meilisearch#137]
Hey guys, first of all thanks for the awesome work you provided!

I have a little question: As described [in your Documentation](https://docs.meilisearch.com/guides/advanced_guides/search_parameters.html#attributes-to-retrieve) there is an option to specify which attributes to receive from a query. I tried to configure it, but sadly it isn't considered in the `transformToMeiliSearchParams`-Function

https://github.com/meilisearch/instant-meilisearch/blob/master/src/index.js#L16-L22

Was there a specific reason to not include this? If not, is there a possibility to add this in a future release?

Thanks!

**Comment by curquiza** [comment]
Hello @aaronschweig! Thanks for paying attention to this kind of detail!

What is exactly your usecase? Do you use an InstantSearch widget/option that allows you to define the attributes you want to retrieve? 🙂

**Comment by aaronschweig** [comment]
Thanks for your quick answer!

I use the [ais-configure Widget](https://www.algolia.com/doc/api-reference/widgets/configure/vue/) to further configure the parameters sent to MeiliSearch. It successfully worked for setting filters. But as i tried setting the `attributesToRetrieve` Property it doesn't appear in the request sent to the server 😄

**Comment by curquiza** [comment]
Thanks for your detailed explanation, it helped me! I fix this issue in this PR #138! 😉

**Comment by aysark** [comment]
I'm facing a similar issue. I'm using vanilla js (instantsearch.js) and i'm not able to configure parameters like filters-- i tried using: `instantsearch.widgets.configure(searchParameters: object);` but it doesn't seem to be doing anything, i think because i'm using addWidgets?

**Comment by curquiza** [comment]
Hello @aysark! I'm not sure this is linked to the `attributesToRecieve` issue. Can you open another one and detail how you use the `configure` widget so that I can fix the bug if it is one? 🙂

**Comment by aysark** [comment]
@curquiza thanks for the response--- but i actually figured it out, so there is no issue:
```
search.addWidgets([
		instantsearch.widgets.configure({
			filters: 'isFeatured = true'
		}),
	]);
```
