### ISSUE TITLE
Errors not caught

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/instant-meilisearch#199]
When using instant meilisearch, if the host or the API key is wrong or the index doesn't exist, the only feedback is an "Uncaught (in promise) Error: Unhandled error. (undefined)" in the console. Those kinds of errors should be caught.

**Comment by bidoubiwa** [comment]
I might have a quick fix for this. Will try it out.

**Comment by bidoubiwa** [comment]
Solved by #216
