### ISSUE TITLE
Search for facet values (searchable) was called, but this client does not have a function client.searchForFacetValues

### ISSUE THREAD

**Issue by gorkagv** [meilisearch/instant-meilisearch#215]
I am trying to set up a facet filter to be able to the ability to filter the refinement list with text input. But I getting this error whenever a key is pressed into the filter input.

"Error: search for facet values (searchable) was called, but this client does not have a function client.searchForFacetValues or client.initIndex(index).searchForFacetValues"

**Comment by curquiza** [comment]
Hello @gorkagv!
Thanks for trying MeiliSearch!

This function does not exist in this client because MeiliSearch does not handle the search in the facet values yet. Sorry for this!

**Comment by angelcervera** [comment]
Hi @curquiza Is this functionality in the roadmap?

**Comment by bidoubiwa** [comment]
Hey @angelcervera, the product repository would be more able to provide a relevant answer https://github.com/meilisearch/product/

It is possible that a discussion is already open on the subject
