### ISSUE TITLE
Fix vulnerability caused by react-scripts

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/instant-meilisearch#226]
We should update to `immer 8>` to fix this vulnerability. This will be possible once `react-scripts` upgrades `immer` version.

See https://github.com/facebook/create-react-app/issues/10411

**Comment by ShrillShrestha** [comment]
Hi, I am a beginner. Can you guide me on how to solve this or is it only possible once the create-react-app's issue is resolved? I think they are still using the 7.0.9 version.

**Comment by bidoubiwa** [comment]
Hey @ShrillShrestha,

Once they have updated `immer` and released a new version, you can update to the next react-scripts. I will keep you updated here :) 

I will also try to add more `good first issue` on our other pending issues that are easily solvable.

**Comment by ShrillShrestha** [comment]
Thanks @bidoubiwa for the information. I will be in the lookout for the `immer`update.

**Comment by bidoubiwa** [comment]
Closed by: #121
