### ISSUE TITLE
Instant Search Pagination Not Working

### ISSUE THREAD

**Issue by KariUs123** [meilisearch/instant-meilisearch#275]
Instant search pagination is not working, it just returns `undefined` on console which means there is no data after clicking the next page, I have tried [this](https://codesandbox.io/s/ms-is-mese9?fontsize=14&hidenavigation=1&theme=dark&file=/index.html) demo also looks like is not working either does any one know why is this happening or is it because of `nbHits` changes and how can I fix this?

**Comment by curquiza** [comment]
This issue should be closed by #273 and the fresh new release (v0.3.1) contains the fix 👍
