### ISSUE TITLE
Use match instead <em> tags

### ISSUE THREAD

**Issue by curquiza** [meilisearch/instant-meilisearch#28]
Currently, we use `<em>` tags and we replace them by the specified tag, but it would be better to use the `match` options in query parameters (during the search) instead.

**Comment by bidoubiwa** [comment]
Since matches do not work when using cropping (see [this issue](https://github.com/meilisearch/MeiliSearch/issues/1490)) is this still something we want?

**Comment by curquiza** [comment]
No sure, feel free to close if you think it's not relevant :)

**Comment by bidoubiwa** [comment]
Closing as `matches` do not correspond to the feature we need
