### ISSUE TITLE
Implement an option for attributesToCrop

### ISSUE THREAD

**Issue by eskombro** [meilisearch/instant-meilisearch#29]
We need to be able to crop fields with instantsearch at search time

**Comment by curquiza** [comment]
This will be available in the v0.2.0 thanks to #50 

⚠️ Snippet (for Algolia) = Crop (for MeiliSearch)

Add `attributeToSnippet` to the [configure widget](https://www.algolia.com/doc/api-reference/widgets/configure/js/)

```js
instantsearch.widgets.configure({
  attributesToSnippet: ['description:50'],
  snippetEllipsisText: '...',
});
```
- `snippetEllipsisText` is not mandatory but will add `...` around your crop string.)
- `:50` is not mandatory and is the cropLength (as a number of chars, not a number of words, contrary to Algolia!)

And then add you cropped attribute in the `hit` widget:
```
instantsearch.widgets.hits({
  container: '#hits',
  templates: {
    item: `
      <h2>{{ name }}</h2>
      <p>{{#helpers.snippet}}{ "attribute": "description" }{{/helpers.snippet}}</p>
    `,
  },
});
```

More about [snippets in Algolia docs](https://www.algolia.com/doc/api-reference/widgets/snippet/js/).
