### ISSUE TITLE
Empty string in search result causes errors

### ISSUE THREAD

**Issue by Jonesus** [meilisearch/instant-meilisearch#371]
If one has an empty string in a search result (instead of, say, `null`) it causes the following error:

![image](https://user-images.githubusercontent.com/16649390/114922574-8615dd80-9e34-11eb-8a99-8eafccb7ce97.png)

The data returned by meilisearch causing the error:
![image](https://user-images.githubusercontent.com/16649390/114922964-f0c71900-9e34-11eb-9316-be29d7533b85.png)

This was tested with `react-instantsearch-dom@6.10.3`, and specific code in my case can be found in https://github.com/Prodeko/prodeko-community/blob/main/src/_pages/Archive/Search.tsx

**Comment by bidoubiwa** [comment]
Hey @Jonesus ! Very sorry to come back to you only now. Your PR flew under the radar. It will be fixed with #403

**Comment by Jonesus** [comment]
Hi @bidoubiwa ! Glad to hear you found the issue, no probs with the timeframe, it's open source after all and was quite easy to account for on my end by not having empty strings :)
