### ISSUE TITLE
Nobel prizes demo url is unreachable in html playground folder

### ISSUE THREAD

**Issue by gmourier** [meilisearch/instant-meilisearch#420]
http://nobel.meilisearch.com/ is unreachable! However, I don't know if the issue should be put directly on this repository? Let me know! I put it here anyway to share it somewhere :)

**Comment by bidoubiwa** [comment]
Hey, it is hosted on codesandbox. https://codesandbox.io/s/nobel-prizes-and-meilisearch-zdy1r?file=/src/main.js:0-23
I think the link you gave is to the meilisearch instance maybe, and if it is in production we do not have access to the dashboard

**Comment by gmourier** [comment]
Thanks @bidoubiwa! I should have mentioned that I followed the link in the README.md https://github.com/meilisearch/instant-meilisearch/blob/main/playgrounds/html/README.md

**Comment by bidoubiwa** [comment]
Ah yes! I will change that :) thanks a lot
