### ISSUE TITLE
Test compatibility with previous versions of instantSearch

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/instant-meilisearch#425]
As for now we only make tests using instantSearch v4, we should also be testing the others to help users determine if they can use instantMeiliSearch

**Comment by curquiza** [comment]
Hum do you mean instant search v3?
The first release of the v4 was released more than 2 years ago. It's not relevant to spend time checking if we are compliant or not with v3 from my POV. Instantsearch v4 is enough. Even for Algolia, 2 years is huge.
But we should indeed note it in the README: we maintain this package for instant-search v4 only.

**Comment by bidoubiwa** [comment]
You thought about it at the same time I did. The PR has been updated with the compatibilities.
