### ISSUE TITLE
`<em>` tags appear inside arrays

### ISSUE THREAD

**Issue by mdubus** [meilisearch/instant-meilisearch#435]
**Description**
By using the v0.21 of MeiliSearch with the version 0.5.0 of Instant MeiliSearch, I receive some fields with `<em>` tags inside.
These tags are not present by using the v0.20 of MeiliSearch. 
This might be fixed with the upgrade of Instant MeiliSearch with the v0.21 of MeiliSearch.

**Expected behavior**
Not sure. Investigation needed to see where it comes from.

**Screenshots or Logs**
v0.20 of MeiliSearch: 

<img width="1434" alt="v20" src="https://user-images.githubusercontent.com/30866152/124578051-238a1780-de4e-11eb-9e48-051055688497.png"> 

v0.21 of MeiliSearch: 

<img width="1434" alt="v21" src="https://user-images.githubusercontent.com/30866152/124578106-33096080-de4e-11eb-8c05-4dc086d6dd5c.png">

**Environment (please complete the following information):**
MeiliSearch v0.21
Instant MeiliSearch v0.5.0

**Comment by curquiza** [comment]
@bidoubiwa can you check upgrading MeiliSearch to v0.21 with your new version of instant-meilisearch fixes this issue?

**Comment by bidoubiwa** [comment]
I put it on `good first issue` for someone to investigate this behavior
