### ISSUE TITLE
Missing addForFacetValue in the SearchClient makes im not compatible for typescript users

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/instant-meilisearch#460]
**Description**

see #48 
Thanks a lot to @haoyun for raising this

When using typescript a searchClient has to response to the search client interface

```ts
export type SearchClient = {
  search: DefaultSearchClient['search'];
  searchForFacetValues: DefaultSearchClient['searchForFacetValues'];
  addAlgoliaAgent?: DefaultSearchClient['addAlgoliaAgent'];
  initIndex?: (
    indexName: string
  ) => SearchIndex extends { findAnswers: any }
    ? Partial<Pick<SearchIndex, 'findAnswers'>>
    : SearchIndex;
};
```
Accessible here: https://github.com/algolia/instantsearch.js/blob/16cc34155d8af25893db3e521b4a1da26ce591e4/src/types/algoliasearch.ts#L33-L42

Until recently it was an optional method.

**Expected behavior**
The method should be present to make instantMeiliSearch usable with typescript

**Current behavior**
As the method is missing it does not work on typescript projects

**Environment (please complete the following information):**

- instantsearch.js version: [e.g. v4.23.0]

**Comment by haoyun** [comment]
I am using `"instantsearch.js": "4.25.1-experimental-typescript.0",` . Currently I forcibly cast `instantMeiliSearch` as `SearchClient`
```
const searchClient = instantMeiliSearch(hostUrl, apiKey, options) as any as SearchClient
```

Typescript support in `instantsearch.js` is still an experimental feature. But their recent releases are all about the TS support.

**Comment by bidoubiwa** [comment]
That is very good to know @haoyun, thanks for checking this out so quickly :) Let me make a fix
