### ISSUE TITLE
populating refinementList

### ISSUE THREAD

**Issue by bnfd** [meilisearch/instant-meilisearch#484]
I'm confused about the left panel (refinementList) in the demo (https://codesandbox.io/s/ms-is-mese9). 
How do I create populate my own refinementList like "genres"? Do I have to set a new attribute for faceting called "genres"? 

The relevant snippet:
```
  instantsearch.widgets.clearRefinements({
    container: "#clear-refinements"
  }),
  instantsearch.widgets.refinementList({
    container: "#genres-list",
    attribute: "genres"
  }),
```
Is `container` only for CSS? 
Does `attribute` "bind" to a facet?

**Comment by bnfd** [comment]
Also, how can I add widgets for new facets dynamically as they get created?

**Comment by bidoubiwa** [comment]
>Do I have to set a new attribute for faceting called "genres"?

Hello @bnfd to add your own refinement/facet/filter to you need to first add them into the settings of your MeiliSearch instance. This [guide](https://docs.meilisearch.com/reference/features/faceted_search.html#setting-up-facets) should help you. 
Once the attribute has been added to the settings you will be able to use it as a refinement! 

> How do I create populate my own refinementList like "genres"?

They are populated automatically based on the values found in MeiliSearch! If you're not satisfied by the way they are rendered you have the possibility to play with the parameters that can be [found here](https://www.algolia.com/doc/api-reference/widgets/refinement-list/js/). Take note some parameters may not be compatible with MeiliSearch yet, see [compatibility](https://github.com/meilisearch/instant-meilisearch/#-refinementlist). 



About the dynamic creation, I'm not sure I understand. do you have a use case? This might be some DOM scripting more than something linked to instant-meilisearch.

**Comment by bidoubiwa** [comment]
Closing due to lack of answer. Feel free to re-open if problem persist
