### ISSUE TITLE
Warning:  Invalid prop: type check failed for prop "showMoreLimit". Expected Number  got String

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/instant-meilisearch#49]
When using `show-more-limit` in `ais-refinement-list` whether the prop is in string or in int the same "error" is thrown in the console. I put error in quotes because it still works even with this error thrown. It work if you put a string or a int.
[Official documentation of showMoreLimit](https://www.algolia.com/doc/api-reference/widgets/refinement-list/vue/#widget-param-show-more-limit)

```bash
Vue warn]: Invalid prop: type check failed for prop "showMoreLimit". Expected Number with value 15, got String with value "15".
```
## Example 

```javascript
<ais-refinement-list attribute="genre" show-more show-more-limit=15 />
```

**Comment by curquiza** [comment]
I get the same error when using Algolia...
Go to [this page](https://codesandbox.io/embed/github/algolia/doc-code-samples/tree/master/Vue+InstantSearch/getting-started) and add `show-more show-more-limit=15` in `App.vue`, line 20.

**Comment by bidoubiwa** [comment]
Fixed in instantSearch v4
