### ISSUE TITLE
InfiniteHits should not over-fetch

### ISSUE THREAD

**Issue by YikSanChan** [meilisearch/instant-meilisearch#521]
**Description**
I am using `SearchBox` and `InfiniteHits` together.

**Expected behavior**
Let's assume there are 1000 search results in total. The `search` API call only gives me 20. After I click "load more", it calls `search` API to fetch the next 20.

**Current behavior**
When I enter the search keyword, the `search` API call gives me 200. After I click "load more", it makes exactly the same API call as its first call.

**Environment (please complete the following information):**
- OS: [e.g. Debian GNU/Linux]
- Browser: [e.g. Chrome version 90.0]
- MeiliSearch version: v.0.21.0
- instant-meilisearch version: v0.5.2
- instantsearch.js version: v6.12.0

**Comment by bidoubiwa** [comment]
Hey @YikSanChan Thanks for you issue! 

To make infiniteHits not depend on `hitsPerPage` which is the option that changes the `limit` to 200 we have to determine the following:

- Is instant-meilisearch is aware of the user widget? Do we know if the user uses `pagination` or `infiniteHits`

### instant-meilisearch is able to tell the difference

if we use inifniteHits: ignore `paginationTotalHits` and use `hitsPerPage` as the limit number. 
if we use `pagination`, use `paginationTotalHits` as the limit

The problem with using `hitsPerPage` as the limit number is that we are not aware if `load more` will still load more hits. 
This should be tested to see if the behavior throws an error. 

### instant-meilisearch is not aware of the difference. 

With the solution provided by #520 the cache will compensate and avoid doing a new search request on every `load more`. But the number of hits will still be limited by `paginationTotalHits`

To determine in which direction we go, we first have to know what information instant-meilisearch receives from instantsearch.
