### ISSUE TITLE
How to configure sort parameter without the sortBy widget

### ISSUE THREAD

**Issue by MoritzLost** [meilisearch/instant-meilisearch#527]
I want to add a default [sort parameter](https://docs.meilisearch.com/reference/features/search_parameters.html#sort) to my InstantSearch page, but I can't figure out how to (statically) add that parameter to the search. The documentation only explains how to pass the sort parameter when interacting with the meilisearch client directly, but I haven't found a way to configure that parameter when using the `instantMeiliSearch` client. I tried to add it using a `configure` widget to no avail. The only thing I can find is the `sortBy` widget, but that is all about exposing the sort options to the user, which I don't want.

How can you statically add a sort parameter to the query executed by an InstantSearch interface?

**Comment by bidoubiwa** [comment]
Hey! Could you give me information about why it didn't work with configure? Do you have a code example of what you tried out?
Also do you maybe have an example of instantSearch making this possible? 
I quickly tried to make a sort with `configure` but I stopped as there was an issue since sortby works with index names, maybe it was different for you. 

I hope we can find it out as I was hoping finding out for myself as well!

**Comment by MoritzLost** [comment]
@bidoubiwa Hi, thanks for the reply! I tried multiple syntaxes for specifiyng the sort parameter, but I couldn't find a resource on how to pass that parameter statically. There's the [documentation page for sorting at search time](https://docs.meilisearch.com/reference/features/sorting.html#sorting-results-at-search-time) which explains how to pass that parameter to the API. Based on this one, the API expects the sort parameter in the format `[attribute]:[asc|desc]`. Then there's [this explainer for the sortBy widget](https://github.com/meilisearch/instant-meilisearch#sort-formula), which requires the index name as well: `[index]:[attribute]:[asc|desc]`.

Based on that, I tried multiple variations for configuring the sort statically (try the commented lines in turn):

```javascript
search.addWidgets([
    configure({
        hitsPerPage: 10,
        // sort: 'postdate:desc',
        // sort: 'search_index:postdate:desc',
        // sort: ['postdate:desc'],
        // sort: ['search_index:postdate:desc'],
    }),
]);
```

Not sure if that is the correct syntax. Anyway, I checked the inspector network tab and the the sort parameter isn't included in the request with any of those variations.

Am I doing it wrong?

**Comment by bidoubiwa** [comment]
Hey @MoritzLost! No you are not, i'm not sure this is possible as we are depedent on how instantsearch communicates the information. I will give it a better look and come back to you asap

**Comment by gpfunk** [comment]
Hey I'm not sure if this is what you're needing, but I managed to do this thru the index name
ie. `movies:date:desc` will use the movies index and sort by date descending. Hope this helps!

**Comment by MoritzLost** [comment]
@gpfunk Thanks for the suggestion! I think I tried that, see my second comment – adding `search_index:postdate:desc` (where `search_index` is the name of the index) to the `configure` widget didn't do anything. Or are you adding this parameter in a different way? It's been a while since I came across this issue, not quite sure I remember all the original context, I'll have to give it a try.

**Comment by gpfunk** [comment]
@MoritzLost I added it straight to InstantSearch component actually
`    <InstantSearch
      indexName="icons:viewBox:asc"
      searchClient={searchClient}`

**Comment by bidoubiwa** [comment]
I think it is fixed, thanks everyone for participating and providing help :)

**Comment by MoritzLost** [comment]
@bidoubiwa Maybe this should be mentioned in the docs somewhere? The docs only mention the [sort parameter](https://docs.meilisearch.com/learn/advanced/sorting.html#using-sort), not sure how to figure out that this parameter is supposed to go on the `indexName` in the context of InstantSearch from there ^^

**Comment by bidoubiwa** [comment]
@MoritzLost if you have some time could you open an issue asking for additional information on this subject in the documentation?

**Comment by qaqland** [comment]
I want my search results sort by "time" only when first empty search. The following search sort as normal.

So it is not possible to change indexName :(

this doesn't work: https://www.algolia.com/doc/api-reference/widgets/instantsearch/react/#widget-param-initialuistate

**Comment by StratusFearMe21** [comment]
I noticed that the value of the sortBy can be controlled with a URL parameter, so I made it so that it automatically sets that URL parameter if it's not set already
```javascript
const urlParams = new URLSearchParams(window.location.search);

if (urlParams.get('journal[sortBy]') == null) {
  urlParams.set('journal[sortBy]', 'journal:published_timestamp:desc');
  window.location.search = urlParams;
}
```

**Comment by natemow** [comment]
Noting here that you can also apply multiple sorts using a comma separator e.g. `search_index:date:desc,featured:desc`
