### ISSUE TITLE
deep object search

### ISSUE THREAD

**Issue by SafaLabash** [meilisearch/instant-meilisearch#556]
**Does anyone have any idea how to work around the missing functionality -search in deep objects  functionality?
for example:
tasks{
category{
name
parent{
name
     }
  }
}
.I want to pass category.name or category.parent.name**

**Comment by bidoubiwa** [comment]
@gmourier could give insight on this

**Comment by gmourier** [comment]
This will be supported by the nested field support addition that we aim to release for v0.27.0.

You will be able to specify .e.g `"filterableAttributes": ["category.parent.name"]`:

**Comment by bidoubiwa** [comment]
In the new version of meilisearch a [nested field feature](https://github.com/meilisearch/specifications/pull/121) is coming which will make it possible to deep search inside objects!
