### ISSUE TITLE
Remove public MeiliSearchClient from the InstantMeiliSearchClient

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/instant-meilisearch#578]
As for now it is possible to use the MeiliSearchClient through instantMeiliSearchClient. For example: 

```js
const cilent = instantMeiliSearch('http://localhost:7700', 'masterKey')
const meilisearchClient = client.MeiliSearchClient
```

While this is handy, ,it also means that every breaking change of `meilisearch-js` is passed to `instant-meilisearch`. 
As it is as heavy to install both packages separately and since it does not add complexity, we should remove `MeiliSearchClient` from the instant meilisearch client.

**Comment by brunoocasali** [comment]
So, if someone wants to use a direct instance of Meilisearch, do they need to add as a dependency and require it directly?

If yes, can we add something about this in the README/Release notes?
