### ISSUE TITLE
Is there a way to pass a URL query parameter into the instant searchbox?

### ISSUE THREAD

**Issue by bwklein** [meilisearch/instant-meilisearch#59]
It works great when I type in the search box field, but I haven't figured out a good method to pass a URL parameter like ?q=training to feed the search system when the page opens.

**Comment by shanebeeston** [comment]
You will need to have routing enabled on instant search, and i believe the default is `?query=` but you will be able to change this by overriding the history router

**Comment by bwklein** [comment]
Thank you,

I was actually reading a bit about that option today.  Do you have a
working example of that somewhere?

**Comment by bidoubiwa** [comment]
Hello @bwklein 
There are two working example in the [playground folder of this repository](https://github.com/meilisearch/instant-meilisearch/tree/master/playgrounds). They both use a remote MeiliSearch to work so you just need to yarn install them and 
`yarn serve` for the vue playground and `yarn start` for the react playground.

Hope you will find your answers.

**Comment by bwklein** [comment]
I found the answers and it is working as of last night! Thank you, closing this case.

Note for others: turn on routing and make sure to set the correct query string in the URL.
In my case it was ?indexname[query]=querystring  ( Ex. ?teci-search[query]=fire )

https://www.femtc.com/search?teci-search%5Bquery%5D=fire works for me!
