### ISSUE TITLE
Add "angular" into GitHub repo topics so that using "angular meilisearch" can find out this repo 

### ISSUE THREAD

**Issue by grimmer0125** [meilisearch/instant-meilisearch#595]

**Comment by bidoubiwa** [comment]
Hey @grimmer0125 
I'm not an angular expert, could you elaborate on what `angular topics` is ?

**Comment by grimmer0125** [comment]
I'm sorry that the issue title is not clear. It just means that adding "angular" to the current GitHub repo topics list: `react client vue js instantserach hacktoberfest meilisearch` which locates below "about" on the right side of the current repo page.

**Comment by bidoubiwa** [comment]
I made the changes, thanks so much for noticing this :) If it is what you expected you can close the issue
