### ISSUE TITLE
Not working with the latest version 0.25.0

### ISSUE THREAD

**Issue by bmpf** [meilisearch/instant-meilisearch#637]
**Description**
Cannot connect to latest version 0.25.0
Package version: "0.25.0"

**Expected behavior**
Status Code: 200

**Current behavior**
Status Code: 401 Unauthorized

**Screenshots or Logs**
Request Method: POST
Status Code: 401 Unauthorized
Referrer Policy: strict-origin-when-cross-origin
code: "missing_authorization_header"
link: "https://docs.meilisearch.com/errors#missing_authorization_header"
message: "The Authorization header is missing. It must use the bearer authorization method."
type: "auth"

**Comment by curquiza** [comment]
Hello @bmpf 

This is a documentation mistake on our side [in the README](https://github.com/meilisearch/instant-meilisearch#-compatibility-with-meilisearch-and-instantsearch) -> this package is not compatible with MeiliSearch v0.25.0 yet. It will be compatible before the end of the week :)

**Comment by curquiza** [comment]
Meanwhile, this beta version is available :)
https://github.com/meilisearch/instant-meilisearch/releases/tag/0.6.0-beta.0

**Comment by bmpf** [comment]
@curquiza  Thank you, trying out the beta version, waiting for the final one :)

**Comment by curquiza** [comment]
[v0.6.0](https://github.com/meilisearch/instant-meilisearch/releases/tag/v0.6.0) is out! 🎉
