### ISSUE TITLE
Cypress tests consitency

### ISSUE THREAD

**Issue by curquiza** [meilisearch/instant-meilisearch#642]
When trying to update this package to be compatible with MeiliSearch v0.25.0, we had some issues with the cypress tests.
We noticed
`Tests / cypress-run` (cf [this file](https://github.com/meilisearch/instant-meilisearch/blob/main/.github/workflows/test.yml)) are not running the same cypress test as `Pre-Release Tests / cypress-run` (cf [this file](https://github.com/meilisearch/instant-meilisearch/blob/main/.github/workflows/pre-release-tests.yml))

`Tests / cypress-run`
- runs using the Vue playground
- runs against a REMOTE MeiliSearch instance (`https://integration-demos.meilisearch.com`)

`Pre-Release Tests / cypress-run`
- runs using the React playground
- runs against a local MeiliSearch instance, downloaded in the CI that will fetch the latest RC

We should
- use the same playground to ensure consistency between the pre-release tests and the others.
- use a local MeiliSearch to run the `Tests / cypress-run` tests. This will avoid update the remote instance to make the tests be green

@bidoubiwa we need your insight before implementing this, you might know why it was done like this. Is there any constraint regarding what I suggest?

**Comment by bidoubiwa** [comment]
I totally agree! See #559 
Tests are only done on the local react server. Tests on other environments where never really done so I removed them. Playgrounds are still running correctly !
