### ISSUE TITLE
How to pass authorization bearer in instant meilisearch 

### ISSUE THREAD

**Issue by gadangmadhulika** [meilisearch/instant-meilisearch#650]
const searchClient = instantMeiliSearch(
    'http://127.0.0.1:7700',
    'masterKey',
    {
      paginationTotalHits: 60,
      primaryKey: 'id',
    }
  )
Using InstantMeiliSearch react https://github.com/meilisearch/meilisearch-react/

**Comment by curquiza** [comment]
Hello, which version of instant-meilisearch are you using?

**Comment by gadangmadhulika** [comment]
HI, Below is the version 0.4.2 and im using latest docker image for meilisearch instance locally and MeiliSearch version is 0.25 and im facing MeiliSearchApiError: The Authorization header is missing. It must use the bearer authorization method in front end. I think we need to pass Authorization bearer in instantMeiliSearrch and how to do that?
const searchClient = instantMeiliSearch(
    'http://127.0.0.1:7700',
    'masterKey',
    {
      paginationTotalHits: 60,
      primaryKey: 'id',
    }
  )

**Comment by gadangmadhulika** [comment]
I updated the Instant-meilisearch with 0.6.0, then the Authorization Bearer error got resolved and i updated react-instantsearch-dom with the latest version 6.20.0.

**Comment by bidoubiwa** [comment]
Hello @gadangmadhulika, thanks for your feedback.
It is indeed linked to the version of instant-meilisearch that is compatible with the latest version of MeiliSearch (v0.25.0)

Happy you solved it :)

**Comment by gadangmadhulika** [comment]
Hi @bidoubiwa 
HI, Im receiving the below error in the front end and iam using "strapi-plugin-meilisearch": "^0.5.0" and "@meilisearch/instant-meilisearch": "^0.6.0" in REACT and v0.25 meilisearch instance on AWS.
Please Help
MeiliSearchCommunicationError
