### ISSUE TITLE
TypeError: this.client.search is not a function

### ISSUE THREAD

**Issue by andyalex234** [meilisearch/instant-meilisearch#665]
Hey guys!  I was using Algolia's `instantsearch` in Next.js project, and I come across this bug ```
Server Error
TypeError: this.client.search is not a function 
```when I try to call `findResultsState (Component, {meilisearchClient, indexName, searchState})` and I looked at the call stack trace and the problem was in `algoiasearch-helper` at `singleIndexSearch` :point_left: this is a helper function that is causing a problem here. meilisearch client object doen't have a search method in its return object rather it is just an empty string. How do we use react instantsearch in SSR environment? does [Instant-MeiliSearch](https://github.com/meilisearch/instant-meilisearch) solve this problem?

**Comment by bidoubiwa** [comment]
To use instant-meilisearch in SSR mode this is how you use it: 

```js
import { instantMeiliSearch } from '@meilisearch/instant-meilisearch'
 import React from 'react';
 import {
   InstantSearch,
   InstantSearchSSRProvider,
 } from 'react-instantsearch-hooks';
 
 const searchClient = instantMeiliSearch('YourApplicationID', 'YourSearchOnlyAPIKey');
 
 function App(props) {
   return (
     <InstantSearchSSRProvider {...props.serverState}>
       <InstantSearch
         indexName="instant_search"
         searchClient={searchClient}
       >
         {/* Widgets */}
       </InstantSearch>
     </InstantSearchSSRProvider>
   );
 }
 
 export default App;
```

**Comment by bidoubiwa** [comment]
Hey @matepaiva could you open a new issue with this question?
