### ISSUE TITLE
Search bar code sample not working

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/instant-meilisearch#689]
**Description**
The search bar code sample in the [getting started](https://github.com/meilisearch/documentation/pull/1466/files) is not working.
I don’t know if this is a bug or there is something wrong with the steps

**Steps**
1. Created an `index.html` file
2. Copied the code
3. Opened `index.html` in Chrome

**Current behavior**
Using the JavaScript code: 
The browser window is blank. The console gives the error:
>Uncaught ReferenceError: instantMeilisearch is not defined
    at index.html:18:21

**Environment (please complete the following information):**
- Browser: Chrome 99.0.4844.51
- Meilisearch version: v.0.26.0
- instant-meilisearch version: 0.3.2
- instantsearch.js version: 4

**Comment by bidoubiwa** [comment]
Thanks a lot I will be checking this!

**Comment by maryamsulemani97** [comment]
> All 3 of them fail?

Yep, same error

**Comment by bidoubiwa** [comment]
After further investigation, the issue came after the rebranding where the `instantMeiliSearch` was unfortunately renamed to `instantMeilisearch` in the HTML examples. 

Could you confirm it works by changing it back to `instantMeiliSearch` @maryamsulemani97 ?

**Comment by maryamsulemani97** [comment]
@bidoubiwa thanks for the update!
The code samples for React, JavaScript, and Vue2 work

**Comment by bidoubiwa** [comment]
<3 Perfect! Closing this issue :)
