### ISSUE TITLE
`AND` operator used on the refinementList widget does not work on react. 

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/instant-meilisearch#694]
As explained [in the documentation of instantsearch], the operator `and` or `or` that you can add to a facet is always applying `or` rules. 

The `and` operator that is considered the one by default is also not the default one, as the default one in all languages is `or`. 

This issue is to keep an eye on the problem and for future users that might wonder why their `and` is not working

**Comment by tadinski** [comment]
Is there a temporary fix to this?

**Comment by bidoubiwa** [comment]
Hey! I tried the or operator again on react and it seems to work! Which version of instantsearch dom are you using? Could you provide every version of packages related to instantsearch ?

**Comment by bidoubiwa** [comment]
Great thanks a lot :)
