### ISSUE TITLE
placeholderSearch option doesn't work in v0.6.2

### ISSUE THREAD

**Issue by tijmenamsing** [meilisearch/instant-meilisearch#709]
**Description**
Setting the configuration property placeholderSearch to false still shows results for me, even though the query is empty. This is contradictory with the documentation.

It used to work correctly in version 0.6.1

**Expected behavior**
Empty query should not trigger a search and not display results.

**Repro**
https://codesandbox.io/s/ms-angularis-forked-cfrjt4?file=/src/app/app.component.ts

**Comment by bidoubiwa** [comment]
I'll look into this, thanks!

**Comment by bidoubiwa** [comment]
It will be fixed in this PR #710

**Comment by tijmenamsing** [comment]
Thanks!
