### ISSUE TITLE
Update .code-samples.meilisearch.yaml

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/instant-meilisearch#728]
⚠️ This issue is generated, it means the examples and the namings do not necessarily correspond to the language of this repository.
Also, if you are a maintainer, feel free to add any clarification and instruction about this issue.

Sorry if this is already partially/completely implemented, feel free to let me know about the state of this issue in the repo.

Related to https://github.com/meilisearch/integration-guides/issues/185

----

Since there is no code-samples in this repository, you should add a new file `.code-samples.meilisearch.yml` into the root of this directory, and add a new key containing the `landing_getting_started_1` contents.
Check out the #185 issue (**Add `landing_getting_started_1` code samples** section) for more information

TODO:

- [x] Add new file `.code-samples.meilisearch.yml`
- [x] Add `landing_getting_started_1` code samples

**Comment by brunoocasali** [comment]
I thought the landing page will only contain instantMeilisearch implementations (vue, react, angular), not the instant meilisearch itself... 🤔

**Comment by bidoubiwa** [comment]
It is the vanilla javascript one!
