### ISSUE TITLE
Allow passed API key to be a callback function

### ISSUE THREAD

**Issue by Zarathustra2** [meilisearch/instant-meilisearch#765]
**Description**
Currently one can only pass in a master key for the search but it would be nice  if we could provide a callback function to set the api key. 

We hide our meilisearch behind a proxy api, if we could add the users token to each request made by instant meili search we could distinguish between different users and then show the user based on their tier (free, premium) the data they have access to.

**Basic example**
```javascript

const searchClient = instantMeiliSearch("", {
  placeholderSearch: false,
  apiKey = () => {
          return localStorage.getItem("TOKEN");
  }
});
```

**Comment by bidoubiwa** [comment]
Hey @Zarathustra2 

Having `apiKey` accept both a string and a function is a great addition. 
I'm open to add this feature for those willing to contribute

**Comment by Zarathustra2** [comment]
Tbh I am not 100% sure if that is needed after thinking about it more. In most cases you gonna have an `Authentication context` anyways and then one can simply do:

```javascript
const { token } = React.useContext(AuthContext);
const [searchClient, setSearchClient] = React.useState(createClient(token));

React.useEffect(() => {
   setSearchClient(createClient(token));
}, [token])
```

But having a callback function might add some more benefits that I am right now missing! :)

**Comment by TheLearneer** [comment]
Hi @bidoubiwa 

I would like to pick it up.
However I just want to know the approach that is being discussed for the actual implementation.

**Comment by a11rew** [comment]
HI @TheLearneer, checking in, are you working on this?

**Comment by TheLearneer** [comment]
Hi @a11rew 👋 

Nope, I got caught up on other things, so you are free to work on it if you want to.
Do follow the instructions from @bidoubiwa though 🙏

**Comment by a11rew** [comment]
Ahh, got it  :+1:
