### ISSUE TITLE
Implement multi-index search

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/instant-meilisearch#774]
Fixed by: #888 

Currently `instant-meilisearch` does not support the [`Index` widget](https://www.algolia.com/doc/api-reference/widgets/index-widget/js/). 

After some research we discovered that the Index widget does not imply merging the search results of multiple index but instead return them in two separate lists (See [this guide of instant-search](https://www.algolia.com/doc/guides/building-search-ui/ui-and-ux-patterns/multi-index-search/js/)).
Thus, we are able to implement it with a small work-around where we make multiple search request.

**Comment by Tragio** [comment]
@bidoubiwa is there any ETA for this? Perhaps 0.29? 🤔 really thank you for your amazing work!!

**Comment by bidoubiwa** [comment]
Hey @Tragio ! I will keep you updated as soon as I have a better idea on when I will be implementing this :)

**Comment by n3a9** [comment]
Hi, just wanted to see here if there was a possible work around to be able to do the multi index search, even if it returns in different lists? I wasn't able to figure out how to trigger multiple index searches from a single query. Thanks :)

**Comment by bidoubiwa** [comment]
The multi-index search beta is released! Can you try it out? It is published on npm [here](https://www.npmjs.com/package/@meilisearch/instant-meilisearch/v/0.10.1-multi-index-search.0)

**Comment by bidoubiwa** [comment]
Released on the latest dist tag on npm 🔥

**Comment by AntoineDuComptoirDesPharmacies** [comment]
Hi @bidoubiwa,

To understand perfect the behavior of this library according to Algolia `multipleQueries` method.
Is this gonna generate one meilisearch search per subquery or it will use the Meilisearch `Multi-search` feature ?
https://www.meilisearch.com/docs/reference/api/multi_search

Thank in advance for your answer !
Yours faithfully,
LCDP
