### ISSUE TITLE
keepZeroFacets not keeping facets with 0 matches when using custom search method with search client

### ISSUE THREAD

**Issue by impzero** [meilisearch/instant-meilisearch#776]
**Description**

Hello, I am trying to preserve the facets from my RefinementList when I select one, but the ones which are not selected disappear.
Let's say we have 3 categories - **clothes**, **shoes**, and **accessories**, clicking on "**clothes**" would hide **shoes** and **accessories** until I unselect **clothes**
I saw in the README that you could provide a `keepZeroFacets` property to the client since version `0.6.2`
I updated my client, set the property to true, and also made sure that my attributes are filterable in the backend. Still, I can't retain the non-chosen categories in the RefinementList

**Expected behavior**

As the documentation from [README ](https://github.com/meilisearch/instant-meilisearch#-customization)states, I expected that after a refinement, facets/filters with 0 matches would still appear in the list

**Current behavior**

As described, currently when refinement finishes, my RefinementList the `items` prop contains only the currentRefinement (for example the selected category - **clothes)**

**Steps to reproduce**

Thankfully I managed to reproduce this in a code sandbox [here](https://codesandbox.io/s/vigilant-brook-sszorg)

**Environment**
- OS: EndeavourOS
- Browser: Chrome Version 102.0.5005.115 (Official Build) (64-bit)
- Meilisearch version: 0.26.1
- instant-meilisearch version: 0.6.2

**Comment by Sidran83** [comment]
We have the same problem, the ulselected facets disappear when one is selected in our efinementList. Is there any fix yet?

**Comment by bidoubiwa** [comment]
Hey! I think this might be linked to #775 but I'm not sure! I will investigate this issue after the pre-release of Meilisearch v0.28.0 ( after 11 july)

**Comment by bidoubiwa** [comment]
Are you using react by any chance?

**Comment by ar-siddiqui** [comment]
I am using react and no matter what I try I can't get 0 facets.

> Are you using react by any chance?

**Comment by bidoubiwa** [comment]
Thanks @ar-siddiqui there seems to be an issue with how React understands the conditionals of facets.

**Comment by bidoubiwa** [comment]
Should be fixed! If it is not, please tell me and re open :)
