### ISSUE TITLE
Enhance security on Meilisearch domain

### ISSUE THREAD

**Issue by vanrijs** [meilisearch/instant-meilisearch#792]
Hi all!

Ive installed this last week on my Vue/Laravel app and it works great.
Due ive indexed a lot of consumer data, I want to secure my meilisearch url as much as possible. 
We use this search option in our CRM so it should not be available to the world.

I tried to add a firewall on meilisearch server and allow only CRM IP but I noticed that the client ip's are doing the requests directly to the meilisearch domain. Another option is to allow also client IPs but if an employee works from another location, I need to add that IP too..

So if you have the domain and key, you can search trough all our indexes all over the world.. What are my options to secure this? 
I was thinking to set host url to an URL from our CRM and do a call so meilisearch from there. In that case all requests are coming from CRM and I get add a firewall..
Is this the way to go of do I have any other options? 

Have a nice day! 
Raymond

**Comment by oluademola** [comment]
Hi @vanrijs, you could use API keys. See more information in the [dedicated documentation](https://docs.meilisearch.com/learn/security/master_api_keys.html#protecting-a-meilisearch-instance).

**Comment by bidoubiwa** [comment]
I'll you open a discussion on the product repo. Closing this as it is not the right repo for that conversation
