### ISSUE TITLE
Clicking "Load More Results" does not always load more pages of results

### ISSUE THREAD

**Issue by chamby** [meilisearch/instant-meilisearch#820]
## Description

@bidoubiwa and I debugged this. Charlotte has a suspicion about where the bug lies.

## Expected behavior

Clicking "Load More Results" with the `ais-infinite-hits` widget should load more results as long as there are more pages of results.

## Current behavior

Clicking "Load More Results" with the `ais-infinite-hits` widget sometimes does not load more results even if there are more pages of results.

`searchContext.pagination.page` is incorrect when building out a `searchContext` resulting in a cached response being used instead of issuing a new network query.

## Screenshots or Logs

Slack discussion: https://meilicommunity.slack.com/archives/C01HTBLHGFL/p1659566578644099

## Environment
- OS: Ubuntu 20.04
- Browser: Firefox 104.0b4
- Meilisearch version: v.0.28.1
- instant-meilisearch version: v0.8.1
- instantsearch.js version: v4.38.0

**Comment by chamby** [comment]
This may not be a problem with Meilisearch after all. I will verify proper behavior once I have updated our production system. I think this issue was manifested by a change in our search function `<ais-instant-search :search-function="searchFunction">` combined with running outdated Meilisearch-related code at the time.

**Comment by bidoubiwa** [comment]
Oh! That would be amazing news. I was still confused about how it could have happened

**Comment by chamby** [comment]
@bidoubiwa Everything seems to be working correctly after fixing an issue in my code and upgrading from v.0.23.x to v.0.28.1
