### ISSUE TITLE
keepZeroFacets does not work with routing

### ISSUE THREAD

**Issue by ar-siddiqui** [meilisearch/instant-meilisearch#825]
**Description**
keepZeroFacets does not work in instant-meilisearch react correctly 

**Expected behavior**
return 0 facets as well

**Current behavior**
does not return 0 facets

Tried both with and without `placeHoloderSearch`

**Comment by bidoubiwa** [comment]
For history 

> In our use case, we do not like the meilisearch API not returning 0 facets. We want to show users to see 0 value facets as well so that they can select them. The hack provided by this [PR](https://github.com/meilisearch/instant-meilisearch/pull/695) only works when you first do a no filter search, if you directly use a URL with specific rules it would not showcase them as the client does not have anything to remember from.

> IMO the meilisearch API should always return 0 facets (or be configurable to return 0 facets) and the client could be configured to either display them or not.

> For example, displaying 0 facets allow a user to add `spreadsheet` as well to the search
![image](https://user-images.githubusercontent.com/53625184/159548177-fb5892da-2730-4548-8c61-55394af5d28c.png)

> But without 0 facets, the user is not even aware that a type `spreadsheet` exists.
> ![image](https://user-images.githubusercontent.com/53625184/159548495-135711aa-ddd7-43d3-b9f1-9fc7f7c1f358.png)

**Comment by bidoubiwa** [comment]
The issue appears in two circumstances:
- When `keepzerofacets` is used with `placeholdersearch: false` (which is not the case here)
- When `keepzerofacets` is used with rooting (which is the case here)

**Comment by ar-siddiqui** [comment]
The issue is there even without routing

**Comment by bidoubiwa** [comment]
In your quoted answer in my comment you are stating 

> directly use a URL with specific rules it would not showcase them as the client does not have anything to remember from.

Could you update your issue with more context to be able to understand the issue?

**Comment by bidoubiwa** [comment]
Hey @ar-siddiqui could you try your bug again with the latest release ? (v0.8.2)

**Comment by ar-siddiqui** [comment]
> Hey @ar-siddiqui could you try your bug again with the latest release ? (v0.8.2)

Ok, I can confirm that this is working and `zerofacets` are displayed, but there is another issue. I will open a new issue to track that.

**Comment by ar-siddiqui** [comment]
> > Hey @ar-siddiqui could you try your bug again with the latest release ? (v0.8.2)
> 
> Ok, I can confirm that this is working and `zerofacets` are displayed, but there is another issue. I will open a new issue to track that.

https://github.com/meilisearch/instant-meilisearch/issues/789#issuecomment-1245718106
