### ISSUE TITLE
GeoSearch with hooks compatibility

### ISSUE THREAD

**Issue by joepio** [meilisearch/instant-meilisearch#877]
Hi there! Thanks for maintaining this awesome library :)

In the algolia docs, the [existing GeoSearch](https://www.algolia.com/doc/api-reference/widgets/geo-search/react/) component seems to become deprecated. Using the new `useConnector` hooks approach is the way to go. It also brings some nice advantages: more control over rendering and behavior, ability to use OpenLayers or Leaflet instead of Google Maps.

In algolia's case, this means we have to use the exported [`connectGeoSearch` from `instantsearch`](https://github.com/algolia/instantsearch.js/blob/master/src/connectors/geo-search/connectGeoSearch.ts). Maybe I'm overlooking something, but I think this is not available in `instant-meilisearch`. I think it would make sense for this project to export something that's compatible with that function. I'd like to request this feature!

**Comment by bidoubiwa** [comment]
Normally it should still be compatible. Instant-meilisearch is a middleware/adaptor between `instantsearch` and `meilisearch-js`. Could you try it?

**Comment by joepio** [comment]
@bidoubiwa Thanks for replying so fast. I don't see an exported `connectGeoSearch` or `GeoSearchContext` in `meilisearch` or `instant-meilisearch`. Maybe I'm overlooking something?

**Comment by bidoubiwa** [comment]
There is actually no import from `instantsearch` inside `instant-meilisearch`. 

What instant-meilisearch is is actually just a client that adapts whatever `instantsearch` provides us to a search request compatible with Meilisearch and then transform the response of Meilisearch to a format `instantsearch` understands.

If you look at their readme: 
```
// 1. Instantiate the search
const search = instantsearch({
  indexName: 'instant_search',
  searchClient: algoliasearch('latency', '6be0576ff61c053d5f9a3225e2a90f76'),
});

```

`instant-meilisearch` is a client like `algoliasearch`. `algoliasearch` does not contain any code related to instant-search (so no `connectGeoSearch` for example). It only contains methods to discuss with your Algolia instance.

**Comment by joepio** [comment]
Thanks for the clarification, but sorry, I still don't understand where I might find `connectGeoSearch` or `GeoSearchContext`. Where should I import the `connectGeoSearch` from then, if it's still compatible?

Maybe my OP was a bit consufing. I want to create a GeoSearch component where users can search using a (custom) map (e.g. OpenLayers or Leaflet). I noticed in the Algolia react-instantsearch docs that the existing `GeoSearch` component is no longer recommended, so users should switch to implementing their own Geo component using the `useConnector` hook, which is provided by `instantsearch` (and `react-instantsearch`, too). 

However, in the [example from the Algolia docs](https://www.algolia.com/doc/guides/building-search-ui/ui-and-ux-patterns/geo-search/react-hooks/), I see that they use a `connectGeoSearch` from their `instantsearch` library. I assume I'd need something similar from meilisearch. 

Thanks again!

**Comment by bidoubiwa** [comment]
You import them from `instantsearch` and use instant-meilisearch as the search client
For example: 

https://codesandbox.io/s/react-movies-demo-e1dqh?file=/src/App.js:180-199

**Comment by joepio** [comment]
You're absolutely right!

I've managed to get pretty much the same UX as with the google component, but this time using MapBox GL. 

Feel free to use it in your docs!

```tsx
import React, {
  useState,
  useEffect,
  useRef,
  useCallback,
  useContext,
  useMemo,
} from "react";
import "./Map.css";
import { useGeoSearch } from "./useGeoSearch";
import MapGL, { FullscreenControl, GeolocateControl, MapRef, Marker } from "react-map-gl";
import { LngLatBounds } from "mapbox-gl";
import "mapbox-gl/dist/mapbox-gl.css";
import { AppContext } from "./App";
import { Gebouw } from "./schema";
import { useSearchBox } from "react-instantsearch-hooks-web";

const mapboxToken =
  "sometoken";

export const mapStartState = {
  latitude: 52.0907,
  longitude: 5.1213,
  zoom: 11,
};

export const startBounds: LngLatBounds = {
  northEast: { lng: 5.213937031523301, lat: 52.15495150795488 },
  southWest: { lng: 5.0036518447552965, lat: 52.03357469016032 },
};

export function Map() {
  const { items, refine } = useGeoSearch();
  const { query } = useSearchBox();
  const { setCurrent, current } = useContext(AppContext);
  const mapRef = useRef<MapRef>();
  const [viewState, setViewState] = React.useState(mapStartState);
  const [prisine, setPristine] = useState(true);

  // If user changed the query, move the bounds to the new items
  useEffect(() => {
    if (!prisine || !mapRef.current) {
      return;
    }
    // Don't set the bounds if there are no items
    if (items.length == 0) {
      return;
    }
    const center = mapRef.current.getMap().getBounds().getCenter();
    let lowLat = center.lat;
    let highLat = center.lat;
    let lowLng = center.lng;
    let highLng = center.lng;
    items.forEach((item, i) => {
      const { lat, lng } = item._geoloc;
      if (i == 0) {
        lowLat = lat;
        highLat = lat;
        lowLng = lng;
        highLng = lng;
      }

      // For some reason the extend method doesn't work, so we do it manually
      // bounds.extend(item._geoloc);
      if (lat < lowLat) {
        lowLat = lat;
      }
      if (lat > highLat) {
        highLat = lat;
      }
      if (lng < lowLng) {
        lowLng = lng;
      }
      if (lng > highLng) {
        highLng = lng;
      }
    });
    let bounds = new LngLatBounds(
      { lat: highLat, lng: highLng },
      { lat: lowLat, lng: lowLng }
    );

    mapRef.current?.fitBounds(bounds, {
      padding: 250,
    });
  }, [prisine, query]);

  // If the user moves the map, update the query to filter current area
  const updateBoundsQuery = useCallback((evt) => {
    if (!evt.originalEvent) {
      return;
    }
    const bounds = mapRef.current.getMap().getBounds();
    refine({
      northEast: bounds.getNorthEast(),
      southWest: bounds.getSouthWest(),
    });
    setViewState(evt.viewState);
  }, []);

  // Memoize markers to prevent rerendering
  const markers = useMemo(
    () =>
      items.map((item) => {
        const isCurrent = item.id == current?.id;
        return (
          <Marker
            onClick={() => setCurrent(item as unknown as Gebouw)}
            longitude={item._geoloc.lng}
            latitude={item._geoloc.lat}
            anchor="bottom"
            // We need this key to make sure the content re-renders, for some reason color changes don't trigger an update
            key={`${item.id} ${isCurrent}`}
            color={isCurrent ? "#000000" : "#FF0000"}
            style={{
              zIndex: isCurrent ? 1 : 0,
            }}
          ></Marker>
        );
      }),
    [items, current]
  );

  return (
    <MapGL
      initialViewState={viewState}
      mapboxAccessToken={mapboxToken}
      onMoveEnd={updateBoundsQuery}
      style={{ width: "100%", height: "100%", flexBasis: "600px", flex: 1 }}
      mapStyle="mapbox://styles/mapbox/streets-v9"
      ref={mapRef}
      attributionControl={false}
    >
      <GeolocateControl position={"bottom-left"} />
      {markers}
    </MapGL>
  );
}
```
