### ISSUE TITLE
Add disjunctive facet search

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/instant-meilisearch#884]
`disjunctiveFacetSearch` changes how we handle multiple facet filters.  See this [spec](https://github.com/meilisearch/product/issues/54) to understand.

To understand better the following explanation, lets consider that we have two facets fields:

- color
    - red
    - blue
- genres
   - drama
   - action

## Current behavior

When performing a search requiring that `color` is `red` and `genres` is `drama`, `instant-meilisearch` is going to perform **ONE** search requests with the following filters:

Only search request:
```
[["genres=drama"], ["color=red"]]
```

Unfortunately, this is not the expected behavior when using facets on most websites.

## Disjunctive facet search

Using disjunctive facet search, we make as many requests as their are different facets filters.

For example, in our case above, we should have made 3 requests.

Search requests: 

first request
```
[["genres:Adventure"], ["color:red"]],
```

Second request:
```
[["color:red"]],
```

Third request:
```
[["genres:Adventure"]],
```

The good news is that `instantsearch` provides us with the required requests. For example, if we ask for color `blue` and genres `Adventure` on a movie index, `instantsearch` provides us with the following objects:

( objects were reduced for readability )
```json
[
  {
    "indexName": "movies",
    "params": {
      "facetFilters": [["genres:Adventure"], ["color:blue"]],
      "facets": ["genres","color"],
      "maxValuesPerFacet": 10,
      "query": "",
      "tagFilters": ""
    }
  },
  {
    "indexName": "movies",
    "params": {
      "facetFilters": [["color:blue"]],
      "facets": "genres",
      "hitsPerPage": 0,
      "maxValuesPerFacet": 10,
      "page": 0,
      "query": ""
    }
  },
  {
    "indexName": "movies",
    "params": {
      "facetFilters": [["genres:Adventure"]],
      "facets": "color",
      "hitsPerPage": 0,
      "maxValuesPerFacet": 10,
      "page": 0,
      "query": ""
    }
  },
]
```

We can then make a search request per element provided by `instantsearch`. Some elements are important to take into account:
- The first request is the default one, lets call it the `hits request`. It returns the hits and uses all the facet filters.
- The following requests, lets call them the `facets requests` are only used to provide the number of documents available for each facet
- The `facets requests` provide us with important field that must overide the current instantsearch context:
    - `hitsPerPage` is either 0 or 1 depending on the instantsearch plugin used. See corner cases
    - `Page` is always 0
    - The field `facets` is provided helping us knowing that this is a `facets requests` and not the `hits request`

## Corner cases

- When using `disjunctive facet search` with a multi index search, all indexes must have the facets added to their `filterableAttributes`.
- disjunctive facet search is only used when the `operator` of `refinementList` is `or`
- Depending on the instantsearch environment the `hitsPerPage` value can be different when performing a facets request. For example in `'react-instantsearch-hooks-web'` hitsPerPage is 0, but in `react-instantsearch-dom` hitsPerPage is 1

**Comment by engel-m** [comment]
I am not sure if the issue I am having is related to this, but for me a weird thing is that I am setting up my project exactly like the code in this example: 

https://codesandbox.io/s/ms-is-mese9?fontsize=14&hidenavigation=1&theme=dark&file=/index.html:952-1057

But for me, disjunctive facetting does not work at all. When I select a facet, it filters correctly, but then removes all other options (which do have a hit count also), as if it were a non disjunctive facet. I can not figure out why the same code does not behave like in the example above.

Am I missing something in configuring the index maybe? Should a facet that is used with disjunctive always be stored as an array in the index f.e.?

**Comment by bidoubiwa** [comment]
Hey @engel-m, are you using the current release of instant-meilisearch or this branch ? #888

**Comment by engel-m** [comment]
@bidoubiwa Update on this:

I have the problem with both branches. 

I found out I was not able to get disjunctive facets to work because I had not configured keepZeroFacets to be set to true.

If I do, I can select multiple options for a facet without the rest disappearing. This would mean that when selecting a facet value, the result count of the other selectable values goes to zero.

**Comment by bidoubiwa** [comment]
Could you show me your configuration? `keepZeroFacets` is not working currently with multi-index/disjunctive facet search. I'm working on fixing that issue.

**Comment by engel-m** [comment]
@bidoubiwa I tried every possible configuration combination there is, but with the exception of `keepZeroFacets` set to `true` and operator `or` , I can not even select multiple values for a facet. Once refined, the rest disappears.

Basically, I have the same problem as in this issue:
https://github.com/meilisearch/instant-meilisearch/issues/789

But when I install your #888 branch it doesn't change anything for me.

**Comment by bidoubiwa** [comment]
Sorry, I may not have been clear. `keepZeroFacets=true` does not work currently on the multi-index search.
See the todo at the end of the body of the PR https://github.com/meilisearch/instant-meilisearch/pull/888

I'm working on the fix :)

**Comment by bidoubiwa** [comment]
It is released on npm :) [Here](https://www.npmjs.com/package/@meilisearch/instant-meilisearch/v/0.10.1-multi-index-search.0)

**Comment by pix2D** [comment]
Is there a way to **force** a particular facet is always taken into account? For example what if we always want to make sure the correct `genre` was returned, but then for other facets we don't care that much and they can fallback to less and less specific filters?

Our specific example is that we have a diets facet in our recipes app, and obviously if someone selects `vegetarian` we do not want to fall back to non-vegetarian recipes. But for all other facets it's fine.

**Comment by bidoubiwa** [comment]
Can the [`and` operator](https://github.com/meilisearch/instant-meilisearch#-refinementlist) solve your issue? Otherwise I would use the [`searchFunction`](https://www.algolia.com/doc/api-reference/widgets/instantsearch/js/#widget-param-searchfunction) or a wrapper around the `instantMeilisearch.search` method to change the value of facets/filters. This guide might [help you](https://docs.meilisearch.com/learn/advanced/filtering_and_faceted_search.html#using-filters)

**Comment by jeremylynch** [comment]
Are we close to getting this one merged in?

**Comment by bidoubiwa** [comment]
It is available in a beta version. You can try it out already :) See [release notes](https://github.com/meilisearch/instant-meilisearch/releases/tag/v0.10.1-multi-index-search.0) on how to try it.

We are waiting for additional feedbacks to merge it

**Comment by MoustafaElsaghier** [comment]
can the same be done through APIs?

**Comment by sparkison** [comment]
Works great! 🎉 thanks so much for implementing this feature 🙏

**Comment by bidoubiwa** [comment]
Hey @MoustafaElsaghier, the multi-index search in the API is in consideration. We are discussing it [here](https://github.com/meilisearch/product/discussions/489). Could you provide the reason why it would be useful to you there?

Thanks a lot for your feedback 🙏

**Comment by MoustafaElsaghier** [comment]
Hello @bidoubiwa, I'm looking for the disjunctive feature to be in API not a multi-index search

to be more clear, I need the disjunctive feature in the same index search same as the main GitHub issue in this thread

**Comment by jeremylynch** [comment]
Hi @bidoubiwa are we close to having this feature out of beta?

**Comment by bidoubiwa** [comment]
Released on the latest dist tag on npm :)
