### ISSUE TITLE
Pagination just show 2 pages

### ISSUE THREAD

**Issue by kamopeter** [meilisearch/instant-meilisearch#956]
Hi there,

sorry for writing here, but I'd like to make a pagination with instant meilisearch (js) like this << < 1 2 3 4 5 6 7 8 ... > 100.
I tried to work with the templates. for example last() { return }. It is return with the full function rendered in words.
I'm sure that I'm lame.

Can you help, how can I manipulate these widget to look like the example, and show more than two page number?

Thanks for your answear

Peter

**Comment by kamopeter** [comment]
Finally I wrote a custom pagination, but still 2 pages return, how can I set, how many pages return.
In addition I use infinite hits.

**Comment by kamopeter** [comment]
I accidentally closed it. I just wanted to wrote, that finally I wrote a custom pagination, but it still return with 2 pages. How can I set to show it more pages?

**Comment by kamopeter** [comment]
Other, if I try to set finitePagination true, I get this in console: MeiliSearchApiError: Json deserialize error: unknown field `hitsPerPage`, expected one of `q`, `offset`, `limit`, `attributesToRetrieve`, `attributesToCrop`, `cropLength`, `attributesToHighlight`, `showMatchesPosition`, `filter`, `sort`, `facets`, `highlightPreTag`, `highlightPostTag`, `cropMarker`, `matchingStrategy` at line 1 column 78

**Comment by oluademola** [comment]
Hello @kamopeter,

Based on the error message, it appears that there is a version incompatibility between the installed instant-meilisearch and Meilisearch. Please keep in mind that the most recent version of instant-meilisearch (v0.10.1) is only compatible with Meilisearch v0.30. Resolving this incompatibility should fix the issue.

Thanks.

**Comment by kamopeter** [comment]
Thanks for your answear. I think a solved the problem.
Thanks a lot
